# Generated by Django 4.0.3 on 2022-04-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefpad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='plural_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
