# Generated by Django 4.0.3 on 2022-04-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefpad', '0003_recipe_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
