# Generated by Django 4.0.3 on 2022-04-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefpad', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('GR', 'grams'), ('TSP', 'Tb'), ('TSP', 'tsp')], default='GR', max_length=3),
        ),
    ]
