# Generated by Django 4.0.3 on 2022-04-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefpad', '0011_alter_recipe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date_added',
            field=models.DateField(null=True),
        ),
    ]
